name: Redeploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACB2SbErYue0bCzC6Hm7+AIjsGuv42TzZveFIK1kFA3ODQAAAKB+y9gyfsvY
MgAAAAtzc2gtZWQyNTUxOQAAACB2SbErYue0bCzC6Hm7+AIjsGuv42TzZveFIK1kFA3ODQ
AAAEBQPogrg7jaVHjmlSZQ7mZPfDYmo/3PUiPyoHYWdD1unXZJsSti57RsLMLoebv4AiOw
a6/jZPNm94UgrWQUDc4NAAAAHXRydW9uZ2Nvbmd0cnVuZzI3MDlAZ21haWwuY29t

      - name: Update server
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 trung@45.76.144.49 "cd vdream-entertainment && git pull && yarn install && yarn build && pm2 restart vdream"
