name: Redeploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update server
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 trung@45.76.144.49 "cd vdream-entertainment && git pull && yarn install && yarn build && pm2 restart vdream"
